# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
